---
### version management
microk8s_disable_snap_autoupdate: false

## plugin configuration
microk8s_plugins:
  dns: true               # CoreDNS
  helm3: true             # Helm 3 - Kubernetes package manager
  ingress: true           # Ingress controller for external access
  metrics-server: true    # K8s Metrics Server for API access to service
                          # metrics
  storage: false          # Storage class; allocates storage from host
                          # directory

microk8s_registry_size: 20Gi

## microk8s_users to make members of microk8s group
microk8s_users:
  - ansible

## enable high-availability?
microk8s_enable_ha: true

## hostgroup whose members will form high-availability cluster
microk8s_group_ha: "microk8s_HA"

# regex to select IP address for joining nodes in HA setup
microk8s_ip_regex_ha: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"
...
