---
# APT::Periodic::Enable "1";
#   Enable the update/upgrade script (0=disable)
unattended_upgrades_enabled: 1

# APT::Periodic::Unattended-Upgrade "1";
#   Run the "unattended-upgrade" security upgrade script
#   every n-days (0=disabled)
#   Requires the package "unattended-upgrades" and will write
#   a log in /var/log/unattended-upgrad
unattended_upgrades_upgrade: 1

# APT::Periodic::Update-Package-Lists "1";
#   Do "apt-get update" automatically every n-days (0=disable)
unattended_upgrades_update_package_list: 1

# APT::Periodic::Download-Upgradeable-Packages "0";
#   Do "apt-get upgrade --download-only" every n-days (0=disable)
# unattended_upgrades_download_upgradeable: 0

# APT::Periodic::AutocleanInterval "0";
#   Do "apt-get autoclean" every n-days (0=disable)
unattended_upgrades_autoclean_interval: 7

# APT::Periodic::CleanInterval "0";
#   Do "apt-get clean" every n-days (0=disable)
unattended_upgrades_clean_interval: 7

# APT::Periodic::Verbose "0";
#   Send report mail to root
#     0:  no report             (or null string)
#     1:  progress report       (actually any string)
#     2:  + command outputs     (remove -qq, remove 2>/dev/null, add -d)
#     3:  + trace on
# unattended_upgrades_verbose: 0

## Cron systems only

# APT::Periodic::RandomSleep
#   When the apt job starts, it will sleep for a random period between 0
#   and APT::Periodic::RandomSleep seconds
#   The default value is "1800" so that the script will stall for up to 30
#   minutes (1800 seconds) so that the mirror servers are not crushed by
#   everyone running their updates all at the same time
#   Kept undefined to allow default (1800)
# unattended_upgrades_random_sleep: 0
...
